version: '3'
services:
  mysql:
    container_name: monolit_mysql
    build: markup/docker/mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./runtime/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
